model:
  type: resnet44
dataset: cifar10
batch: 256
epoch: 200
mask: 'advmask'
lr: 0.1
writer: False
# lr_schedule:
#   warmup: ''
#   type: 'step'
#   milestones: [60, 120, 160, 240, 300, 360, 420, 460]
#   gamma: 0.1
lr_schedule:
  type: 'cosine'
  warmup: 
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0002
  ema: 0
  momentum: 0.9