model:
  type: resnet101
dataset: cifar10
batch: 128
epoch: 500
lr: 0.1
# lr_schedule:
#   warmup: ''
#   type: 'step'
#   milestones: [150, 225, 350, 425]
  # gamma: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0002
  ema: 0