model:
  type: shakeshake26_2x112d
dataset: cifar100
batch: 512
epoch: 1800
lr: 0.01
adv_mask:
  lower: 3
  upper: 20
  mask_scope: 0.7
  conflict_ratio: 0.2
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
  # warmup: ''
  # type: 'step'
  # # milestones: [150, 250, 350, 500, 600, 700, 800, 900,425]
  # milestones: [60, 120, 160, 240, 300, 360, 420, 460]
  # gamma: 0.2
optimizer:
  type: sgd
  nesterov: True
  decay: 0.002
  ema: 0