model:
  type: shakeshake26_2x32d
# batch: 512
# epoch: 1800
# writer: False
# lr: 0.2
# lr_schedule:
#   type: 'cosine'
#   warmup:
#     multiplier: 1
#     epoch: 5
# optimizer:
#   type: sgd
#   nesterov: True
#   decay: 0.001
#   ema: 0


batch: 128
epoch: 1800
mask: 'fast-autoaugment'
writer: False
lr: 0.01
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
  ema: 0