model:
  type: wresnet28_10
batch: 128
epoch: 300
lr: 0.1
writer: False
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 2
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
 